version: '3'
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile.env
      context: ./server
    ports:
      - 4000:4000
    networks: 
      - backend
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.env
      context: ./client
    ports:
      - 80:80
    networks: 
      - backend
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27018:27017
    networks: 
      - backend

networks: 
  backend:
    driver: bridge